services:  
  - type: web    
    name: telegram-bot    
    env: python    
    buildCommand: ""    
    startCommand: python telegram_bot.py    
    envVars:      
      - key: BOT_TOKEN        
        sync: false      
      - key: CHAT_ID        
        sync: false